version: "2.1"
services:
  redvblue:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: redvblue
    shm_size: '4gb' # for the shared memory size
    volumes:
      - ~/.commune:/root/.commune # mount the temporary folder
      - ./:/app # mount the current directory
    ports:
      - 50050-50250:50050-50250

    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

    restart: unless-stopped
